Support large file upload
odrive/gateway-api pull request #10
Opened 2022-06-03 21:34 UTC by warofworlds

2022-06-03 22:26 UTC, terrenceyee requested changes

2022-06-03 22:26 UTC, terrenceyee commented on gateway-api.md
> +`gateway.metadata.file.hash` | Files with the same hash have the same bytes
Update description to match earlier update.

2022-06-03 22:26 UTC, terrenceyee commented on gateway-api.md
> +`gateway.upload.segment` | List of updated upload segments.
gateway.upload.segments (with an s)?

2022-06-03 22:26 UTC, terrenceyee commented on gateway-api.md
> +`gateway.upload.segment.memo` | Opaque gateway information
The response returns different segment information. For procore, an eTag is returned for the segment. It doesn't need to return url and headers. Should the return property also be named "gateway.upload.segment.memo", or something else like "gateway.upload.segment.result"?

2022-06-03 22:26 UTC, terrenceyee commented on gateway-api.md
> +`gateway.upload.segment` | List of updated upload segments
List of updated upload segments from the segmented upload requests.

2022-06-03 22:46 UTC, warofworlds commented on gateway-api.md
> +`gateway.upload.segment` | List of updated upload segments.
I'm using type as name .... so no s

2022-06-05 19:10 UTC, terrenceyee approved these changes

2022-06-11 02:46 UTC, merged